### ISSUE TITLE
Request: add udev rule for the mayflash dolphinbar

### ISSUE THREAD

**Issue by chowder3907** [ValveSoftware/steam-devices#41]
As it stands right now, in order to use wii remotes as native for emulators such as dolphin, you must go into desktop mode and close steam so that it does not interfere with the dolphinbar and wii remotes. A reddit post suggests adding [these udev rules](https://github.com/dolphin-emu/dolphin/blob/master/Data/51-usb-device.rules) to make the dolphinbar work, however I have not verified this. At the least I would like a way to stop steam input from taking over my dolphinbar and wii remotes. This happens on my steam deck where I want this as well as on my normal desktop with steam.

**Comment by smcv** [comment]
For the Gamecube controller adapter and the Dolphinbar, if you run

```
~/.steam/root/ubuntu12_32/steam-runtime/run.sh steam-runtime-input-monitor
```

with all desired devices unplugged, wait for it to finish describing all your other devices (it should say `{"all-for-now": true}` at the end), and then plug these devices in, what additional information is displayed after the `{"all-for-now": true}` marker?

Press Ctrl+C to stop the input monitor when it has finished displaying the new device(s).

Having that information will help to avoid regressions in SDL for these devices.

I'm not sure whether udev rules for unconventional Nintendo controllers are in-scope for this repository. The udev rules in this repo are for Steam Input (dealing with more conventional gamepads that are basically the same shape as Steam Controller, Xbox 360 or newer, PS3 or newer, and Switch classic controllers) and SteamVR, but Wiimotes aren't really compatible with any of those, and arguably neither are Gamecube controllers.

If Steam Input is suppressing input from Wiimotes and shouldn't be, then that seems like probably something that should be solved inside Steam, rather than by adding unrelated udev rules. @slouken might have some insight into what's going on there?

**Comment by smcv** [comment]
> Steam no longer tries to open Wiimotes and dolphinbar, FYI.

Does it also avoid suppressing detection of Wiimotes and the Dolphinbar in Steam games and Dolphin?

If so, then I think this issue report might have become obsolete.

**Comment by slouken** [comment]
Yep

**Comment by kisak-valve** [comment]
Closing per the last couple comments.
